### ISSUE TITLE
access to Scheitinger2017_exp.RData

### ISSUE THREAD

**Issue by cdkodira** [hamid-bolouri/TCE#1]
I dont't see this file (Scheitinger2017_exp.RData) anywhere in the directory. 
Where can I find this file?
Thanks
Kodira

**Comment by hamid-bolouri** [comment]
I think I found it. See attached.

Best of luck!

Hamid

**Comment by cdkodira** [comment]
Dear Hamid,
Thanks for your quick response. I don't see any attachment.
Thanks,
D Kodira

**Comment by hamid-bolouri** [comment]
hmmm, not sure why. IIn any case,  added the file to the repository:

https://github.com/hamid-bolouri/TCE/blob/master/Scheitinger2017_exp.RData

Please note this file is really just my verison of GSE89307. We analyzed many GEO data sets, as detailed in the paper. Please download other such files directly from GEO.

Good luck!

Hamid

**Comment by cdkodira** [comment]
Super. Thank you very much.

________________________________
