### ISSUE TITLE
Warning message: In file(con, "r") :   cannot open file 'TexSimCmds.R': No such file or directory

### ISSUE THREAD

**Issue by geenaildefonso** [hamid-bolouri/TCE#2]
In running [simRandTex.R](https://github.com/hamid-bolouri/TCE/blob/master/simRandTex.R) file, error message when running code returning: 
```
Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file 'TexSimCmds.R': No such file or directory
```
This file [TexSimCmds.R] is not inside the repository, any help is appreciated. Thank you!

**Comment by hamid-bolouri** [comment]
Hi Geena; Thanks for spotting the issue. 

Alex Ratushny did some outstanding detective work and was able to locate the missing file.  I have now added the file to the repository. Additionally, attaching the file here, for the record (note I added a '.txt' suffix to enable github attachment). 

[TexSimCmds.R.txt](https://github.com/hamid-bolouri/TCE/files/9022187/TexSimCmds.R.txt)
